### ISSUE TITLE
The version of this README at http://f5-openstack-lbaasv2.readthedocs.org does not match the tip of master

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-openstack-lbaasv2#25]
@jputrino @richbrowne @jlongstaf 

This may be by design (I'm not sure) but there are bugs in the RTD version that are fixed in the github "master" version.

In particular the pip installs on RTD fail because they are missing a "v" that is present on the github version.

**Comment by jputrino** [comment]
We are aware of this. It's a result of the content in the release version on RTD corresponding to how it appears in GitHub at the time the release is made. The updates were made after the release, so they don't get included in the tagged release version on RTD. @swormke and I decided not to do a new release just to get the updates into RTD because they do appear in the 'latest' version.

**Comment by zancas** [comment]
@jputrino @swormke what's our release policy with-respect-to documentation bugfixes?

**Comment by jputrino** [comment]
We don't really have one, officially, as of yet. In this repo I've set up a webhook so the 'latest' version of the docs will update automatically when a commit is made here (aka, when a pull request is merged). In order to get the change into the release here, I think I'd have to delete it and make a new one (which I'm open to).

**Comment by zancas** [comment]
This seems like a policy decision for @swormke to me.
